# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(393, 96)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.ebootLabel = QtWidgets.QLabel(self.centralwidget)
        self.ebootLabel.setObjectName("ebootLabel")
        self.gridLayout.addWidget(self.ebootLabel, 1, 2, 1, 1)
        self.pathLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.pathLineEdit.setObjectName("pathLineEdit")
        self.gridLayout.addWidget(self.pathLineEdit, 0, 1, 1, 1)
        self.apllyButton = QtWidgets.QPushButton(self.centralwidget)
        self.apllyButton.setObjectName("apllyButton")
        self.gridLayout.addWidget(self.apllyButton, 1, 0, 1, 1)
        self.pathLabel = QtWidgets.QLabel(self.centralwidget)
        self.pathLabel.setObjectName("pathLabel")
        self.gridLayout.addWidget(self.pathLabel, 0, 2, 1, 1)
        self.BrowseButton = QtWidgets.QPushButton(self.centralwidget)
        self.BrowseButton.setObjectName("BrowseButton")
        self.gridLayout.addWidget(self.BrowseButton, 0, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setObjectName("comboBox")
        self.gridLayout.addWidget(self.comboBox, 1, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 2, 0, 1, 3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.ebootLabel.setText(_translate("MainWindow", "Change Selected EBOOT"))
        self.apllyButton.setText(_translate("MainWindow", "Apply"))
        self.pathLabel.setText(_translate("MainWindow", "RPCS3.exe Path"))
        self.BrowseButton.setText(_translate("MainWindow", "Browse"))
